# Task 1: Python Proficiency Check – AI Bootcamp Prep

## Section 1: Basics & Control Flow

In [ ]:
def fizzbuzz_ai_bootcamp():
  for i in range(1,51,1):
    if i%3==0:
      print(f"{i}=AI")
    elif i%5==0:
      print(f"{i}=Bootcamp")
    else:
      print(i)

fizzbuzz_ai_bootcamp()

1
2
3=AI
4
5=Bootcamp
6=AI
7
8
9=AI
10=Bootcamp
11
12=AI
13
14
15=AI
16
17
18=AI
19
20=Bootcamp
21=AI
22
23
24=AI
25=Bootcamp
26
27=AI
28
29
30=AI
31
32
33=AI
34
35=Bootcamp
36=AI
37
38
39=AI
40=Bootcamp
41
42=AI
43
44
45=AI
46
47
48=AI
49
50=Bootcamp


### **Task 2**: List Comprehensions and Functions

*Instruction*: Given a list of numbers, square only the even numbers using a list comprehension and define a function that returns the result.

In [ ]:
def square_evens(numbers):
    return [x**2 for x in numbers if x % 2 == 0]

print(square_evens([1, 2, 3, 4, 5, 6]))


[4, 16, 36]


## Section 2: Data Structures & File I/O

### **Task 3**: Word Frequency from a File

*Instruction*: Read the provided text file (Sample_For_Task1.txt) and return the 5 most common words (ignoring punctuation and case).

In [ ]:
from collections import Counter
import string
def top_5_words(filepath):
  with open(filepath, 'r') as file:
        text = file.read()
        text= text.lower()
  text = text.translate(str.maketrans('', '', string.punctuation))
  words = text.split()
  word_counts = Counter(words)
  most_common = word_counts.most_common(5)
  for word, count in most_common:
    print(f"{word}: {count}")


top_5_words('/content/sample_data/README.md')

is: 4
a: 3
the: 3
sample: 2
at: 2


## Section 3: NumPy & pandas

### **Task 4**: NumPy Matrix Magic

*Instruction*: Create a 5x5 matrix with random integers from 1 to 10. Replace all elements greater than 5 with 0.

In [ ]:
import numpy as np

def matrix_transform():
    # Step 1: Create a 5x5 matrix with random integers from 1 to 10
    matrix = np.random.randint(1, 11, size=(5, 5))
    print("Original matrix:\n", matrix)

    # Step 2: Replace all elements greater than 5 with 0
    matrix[matrix > 5] = 0
    print("\nTransformed matrix:\n", matrix)

# Call the function
matrix_transform()


Original matrix:
 [[ 1  8  8  9  4]
 [ 8  3  7  4 10]
 [ 5  3  3  4  3]
 [ 9  6  7  6  1]
 [ 6  5  6  2  4]]

Transformed matrix:
 [[1 0 0 0 4]
 [0 3 0 4 0]
 [5 3 3 4 3]
 [0 0 0 0 1]
 [0 5 0 2 4]]


### **Task 5**: pandas DataFrame Manipulation

*Instruction*: Given the following dictionary, convert it into a DataFrame, calculate the average score per student, and add it as a new column.

In [ ]:
import pandas as pd

# Provided data dictionary
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Math': [85, 78, 92],
    'Science': [90, 88, 84],
    'English': [87, 85, 80]
}

# Convert dictionary to DataFrame
df = pd.DataFrame(data)

# Calculate average score across subjects and add it as a new column
df['Average'] = df[['Math', 'Science', 'English']].mean(axis=1)

# Display the final DataFrame
print(df)


      Name  Math  Science  English    Average
0    Alice    85       90       87  87.333333
1      Bob    78       88       85  83.666667
2  Charlie    92       84       80  85.333333


## Section 4: Visualization & Logic

### **Task 6**: Simple Data Visualization

*Instruction*: Use matplotlib to create a bar chart showing the average score per subject from the DataFrame in the previous task.

In [ ]:
import matplotlib.pyplot as plt

# Data from the previous task
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Math': [85, 78, 92],
    'Science': [90, 88, 84],
    'English': [87, 85, 80]
}

# Create DataFrame
df = pd.DataFrame(data)

# Calculate average score per subject (mean across rows)
subject_averages = df[['Math', 'Science', 'English']].mean()


## Section 5: Mini-Project Challenge

### **Task 7**: Build a Mini Calculator with Exception Handling

*Instruction*: Write a function that takes two numbers and an operator as input (+, -, *, /). Return the result, and handle divide-by-zero and invalid operator cases with appropriate error messages.

In [ ]:
def calculate(num1, num2, operator):
    try:
        if operator == '+':
            return num1 + num2
        elif operator == '-':
            return num1 - num2
        elif operator == '*':
            return num1 * num2
        elif operator == '/':
            if num2 == 0:
                return "Error: Cannot divide by zero."
            return num1 / num2
        else:
            return "Error: Invalid operator. Use one of '+', '-', '*', '/'."
    except Exception as e:
        return f"An error occurred: {e}"

# 🔍 Example usage:
print(calculate(10, 5, '+'))  # Output: 15
print(calculate(10, 0, '/'))  # Output: Error: Cannot divide by zero.
print(calculate(10, 3, '^'))  # Output: Error: Invalid operator



15
Error: Cannot divide by zero.
Error: Invalid operator. Use one of '+', '-', '*', '/'.
